/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-dim": "var(--color-surface-dim, #0d141d)",
        "outline": "var(--color-outline, #958da1)",
        "on-secondary-container": "var(--color-on-secondary-container, #e8aaff)",
        "primary": "var(--color-primary, #e088ff)",
        "on-background": "var(--color-on-background, #dce3f0)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim, #dd88ff)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim, #cc77ee)",
        "outline-variant": "var(--color-outline-variant, #4a3055)",
        "surface-container-lowest": "var(--color-surface-container-lowest, #080f17)",
        "tertiary-container": "var(--color-tertiary-container, #007650)",
        "surface-variant": "var(--color-surface-variant, #2e1f40)",
        "primary-container": "var(--color-primary-container, #9900AA)",
        "on-surface": "var(--color-on-surface, #dce3f0)",
        "error-container": "var(--color-error-container, #93000a)",
        "on-tertiary-container": "var(--color-on-tertiary-container, #76ffc2)",
        "secondary-fixed": "var(--color-secondary-fixed, #f2d8ff)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant, #6a0077)",
        "primary-fixed": "var(--color-primary-fixed, #faeeff)",
        "surface": "var(--color-surface, #0d141d)",
        "inverse-primary": "var(--color-inverse-primary, #9900AA)",
        "tertiary-fixed": "var(--color-tertiary-fixed, #6ffbbe)",
        "tertiary": "var(--color-tertiary, #4edea3)",
        "inverse-surface": "var(--color-inverse-surface, #dce3f0)",
        "surface-container": "var(--color-surface-container, #192029)",
        "on-surface-variant": "var(--color-on-surface-variant, #d8bbee)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed, #002113)",
        "on-primary-container": "var(--color-on-primary-container, #faeeff)",
        "on-secondary": "var(--color-on-secondary, #2d0044)",
        "surface-tint": "var(--color-surface-tint, #e088ff)",
        "on-error": "var(--color-on-error, #690005)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant, #6a0077)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant, #005236)",
        "inverse-on-surface": "var(--color-inverse-on-surface, #2a313b)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed, #2d0044)",
        "secondary-container": "var(--color-secondary-container, #6a0077)",
        "on-tertiary": "var(--color-on-tertiary, #003824)",
        "surface-container-high": "var(--color-surface-container-high, #232a34)",
        "on-primary-fixed": "var(--color-on-primary-fixed, #2d0044)",
        "background": "var(--color-background, #0d141d)",
        "surface-container-low": "var(--color-surface-container-low, #151c25)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim, #4edea3)",
        "surface-bright": "var(--color-surface-bright, #333a44)",
        "secondary": "var(--color-secondary, #cc88ee)",
        "error": "var(--color-error, #ffb4ab)",
        "on-primary": "var(--color-on-primary, #ffffff)",
        "surface-container-highest": "var(--color-surface-container-highest, #2e353f)",
        "on-error-container": "var(--color-on-error-container, #ffdad6)"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "max-width": "1440px",
        "sm": "12px",
        "2xl": "48px",
        "base": "4px",
        "md": "16px",
        "lg": "24px",
        "gutter": "20px",
        "xl": "32px",
        "margin-desktop": "32px",
        "margin-mobile": "16px",
        "xs": "8px"
      },
      fontFamily: {
        "label-md": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "mono-code": ["JetBrains Mono", "monospace"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-xl": ["Geist", "sans-serif"],
        "headline-lg-mobile": ["Geist", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-sm": ["Geist", "sans-serif"]
      },
      fontSize: {
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "mono-code": ["13px", { "lineHeight": "20px", "fontWeight": "400" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-xl": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
